language: python

sudo: false

env:
  global:
    - TOXENV=''
    - TOXARGS=''
    - TOXPOSARGS=''

matrix:

  include:

    # Run the default test environment on
    # all major platforms

    - os: linux
      python: 3.8
      env: TOXENV='test'

    - os: linux
      python: 3.6
      env: TOXENV='test'

    # Run the test-dev-all environment and pass the
    # --remote-data to demonstrate passing positional
    # arguments for pytest
    - os: linux
      python: 3.7
      env: TOXENV="test-all-dev"
        TOXPOSARGS="--remote-data=astropy"

    # Build the docs
    - os: linux
      python: 3.7
      env: TOXENV="build_docs"

    # Run pycodestyle checks
    - os: linux
      python: 3.7
      env: TOXENV="flake8"

    # Run with jwst pipeline
    - os: linux
      python: 3.7
      env: PIP_DEPENDENCIES="$PIP_DEPENDENCIES git+https://github.com/spacetelescope/jwst@stable"

  allow_failures:
    # Currently, travis does not support python language jobs in builds.
    - os: windows
      python: 3.7
      env: TOXENV='test'

before_install:

  # We need a full clone to make sure setuptools_scm
  # works properly
  - git fetch --unshallow .
  - git fetch --depth=1000000

install:
  - pip install tox --upgrade

script:
  - tox -e $TOXENV $TOXARGS -- $TOXPOSARGS

after_success:
  - pip install codecov
  - codecov
